### ISSUE TITLE
"slice bounds out of range" on kompose conversion

### ISSUE THREAD

**Issue by azerpas** [dunglas/symfony-docker#114]
Every time I'm trying to convert my `docker-compose.yml` to a container orchestrator through [Kompose](https://github.com/kubernetes/kompose), I'm getting this error. 

```kompose convert
WARN Restart policy 'unless-stopped' in service caddy is not supported, convert it to 'always'
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/kubernetes/kompose/pkg/loader/compose.parseHealthCheck(0x0, 0x0, 0x0, 0xc000267970, 0xc000267980, 0xc000267990, 0xc000267998, 0x0, 0x0, 0x0, ...)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:270 +0x46f
github.com/kubernetes/kompose/pkg/loader/compose.dockerComposeToKomposeMapping(0xc00050a300, 0x0, 0x0, 0x0, 0xc00039f980, 0x1, 0x1)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:334 +0xbe4
github.com/kubernetes/kompose/pkg/loader/compose.parseV3(0xc000410980, 0x1, 0x1, 0x3, 0xffffffffffffffff, 0x1, 0x1, 0x2fb4f40, 0x1013601)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/v3.go:129 +0x1ac
github.com/kubernetes/kompose/pkg/loader/compose.(*Compose).LoadFile(0x280e678, 0xc000410980, 0x1, 0x1, 0x0, 0x0, 0x200000003, 0xc000000180, 0x0, 0xc0002dfa38)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/pkg/loader/compose/compose.go:180 +0x37f
github.com/kubernetes/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x1ddb660, 0x4, 0x1, 0x1debc77, 0x15, ...)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/pkg/app/app.go:224 +0x11e
github.com/kubernetes/kompose/cmd.glob..func3(0x27dcc40, 0x280e678, 0x0, 0x0)
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/cmd/convert.go:106 +0x4d
github.com/spf13/cobra.(*Command).execute(0x27dcc40, 0x280e678, 0x0, 0x0, 0x27dcc40, 0x280e678)
	/home/wikus/syncthing/files/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x27dcee0, 0x103b11a, 0x2792260, 0xc000060750)
	/home/wikus/syncthing/files/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/wikus/syncthing/files/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/kubernetes/kompose/cmd.Execute()
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/cmd/root.go:92 +0x31
main.main()
	/home/wikus/syncthing/files/dev/go/src/github.com/kubernetes/kompose/main.go:22 +0x20
```

It seems like it's related to Symfony https://github.com/symfony/cli/issues/124.

Happened to anyone?

**Comment by maxhelias** [comment]
I'm not sure if it's related because SymfonyCLI and Kompose are 2 different projects and this projet doesn't use SymfonyCLI. It's probably the same bug.
You should instead open an issue on the Kompose project, if it is not already fixed because we can't do anything here.
