### ISSUE TITLE
Unable to start containers

### ISSUE THREAD

**Issue by syntaxgirl** [dunglas/symfony-docker#115]
I just wanted to try this docker setup, and cloned it to my local system. Once done, I used `docker-compose up` to start containers but failed.

```
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in phar:///usr/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 phar:///usr/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php(387): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php(740): Composer\DependencyResolver\Solver->selectAndInstall()
#4 phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php(231): Composer\DependencyResolver\Solver->runSat()
#5 phar:///usr/bin/composer/src/Composer/Installer.php(489): Composer\DependencyResolver\Solver->solve()
#6 phar:///usr/bin/composer/src/Composer/Installer.php(232): Composer\Installer->doInstall()
#7 phar:///usr/bin/composer/src/Composer/Command/InstallCommand.php(122): Composer\Installer->run()
#8 phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\InstallCommand->execute()
#9 phar:///usr/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#10 phar:///usr/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#11 phar:///usr/bin/composer/src/Composer/Console/Application.php(281): Symfony\Component\Console\Application->doRun()
#12 phar:///usr/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#13 phar:///usr/bin/composer/src/Composer/Console/Application.php(113): Symfony\Component\Console\Application->run()
#14 phar:///usr/bin/composer/bin/composer(61): Composer\Console\Application->run()
#15 /usr/bin/composer(24): require('...')
#16 {main}
  thrown in phar:///usr/bin/composer/src/Composer/DependencyResolver/DefaultPolicy.php on line 84
ERROR: Service 'php' failed to build : The command '/bin/sh -c set -eux; 	mkdir -p var/cache var/log; 	composer install --prefer-dist --no-dev --no-progress --no-scripts --no-interaction; 	composer dump-autoload --classmap-authoritative --no-dev; 	composer symfony:dump-env prod; 	composer run-script --no-dev post-install-cmd; 	chmod +x bin/console; sync' returned a non-zero code: 255
```
My system docker-compose version: `docker-compose version 1.27.4, build 40524192` and docker `Docker version 19.03.13, build 4484c46d9d`

Anyone know's what could be the issue?

**Comment by syntaxgirl** [comment]
Issue was with my local system. I had an old composer:latest image, which I pulled long time ago. You can fix it by running
`docker pull composer:latest` before `docker-compose up`.
