### ISSUE TITLE
Unable to start Caddy container

### ISSUE THREAD

**Issue by ker0x** [dunglas/symfony-docker#124]
Hello

I'm facing this error when running `docker-compose up`.

It occurs on both Ubuntu and Windows (through WSL2)

```bash
caddy_1  | goroutine 1 [running]:
caddy_1  | google.golang.org/protobuf/reflect/protoregistry.glob..func1(0x1c5a1a0, 0xc0001b3a40, 0x1c26000, 0xc0002b0d00, 0xc0001b3a40)
caddy_1  | 	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:54 +0x25f
caddy_1  | google.golang.org/protobuf/reflect/protoregistry.(*Files).RegisterFile(0xc000096ff0, 0x1c631e0, 0xc0001b3a40, 0x0, 0x0)
caddy_1  | 	google.golang.org/protobuf@v1.26.0/reflect/protoregistry/registry.go:127 +0xb72
caddy_1  | google.golang.org/protobuf/internal/filedesc.Builder.Build(0x0, 0x0, 0xc00030e600, 0x47a, 0x600, 0x800000003, 0x0, 0x1c39740, 0xc000099950, 0x1c42bc0, ...)
caddy_1  | 	google.golang.org/protobuf@v1.26.0/internal/filedesc/build.go:113 +0x1aa
caddy_1  | github.com/golang/protobuf/proto.RegisterFile(0x196f943, 0x8, 0x262f920, 0x2b3, 0x2b3)
caddy_1  | 	github.com/golang/protobuf@v1.5.2/proto/registry.go:48 +0x147
caddy_1  | github.com/dgraph-io/badger/v2/pb.init.1()
caddy_1  | 	github.com/dgraph-io/badger/v2@v2.2007.2/pb/pb.pb.go:650 +0x5a
caddy_1  | panic: proto: file "pb.proto" is already registered
caddy_1  | See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

**Comment by DavidFeller** [comment]
I'm facing the same problem on MacOS.

**Comment by mindtechmedia** [comment]
Same here. Fresh ubuntu 20.04/docker installation

**Comment by dunglas** [comment]
It's probably related to https://github.com/caddyserver/caddy/issues/3525. I'm taking a look.

**Comment by dunglas** [comment]
This PR should fix the problem: https://github.com/dunglas/symfony-docker/pull/125
Can you try if it works for you? Thanks!

**Comment by ker0x** [comment]
@dunglas it works fine with the fix, thanks you!
