### ISSUE TITLE
Error on docker-compose build on existing project

### ISSUE THREAD

**Issue by 0-Yorick-0** [dunglas/symfony-docker#236]
Hi, and thx a lot for this project that brings a lot of help.

Today I encountered an error that I can't solve when I run `docker-compose up --build -d`:

```
#21 3.258 Run composer recipes at any time to see the status of your Symfony recipes.
#21 3.258
#21 3.293 + composer dump-autoload --classmap-authoritative --no-dev
#21 3.441 Generating optimized autoload files (authoritative)
#21 4.089 Generated optimized autoload files (authoritative) containing 1363 classes
#21 4.099 + composer symfony:dump-env prod
#21 4.254 Successfully dumped .env files in .env.local.php
#21 4.264 + composer run-script --no-dev post-install-cmd
#21 4.424
#21 4.424 Run composer recipes at any time to see the status of your Symfony recipes.
#21 4.424
#21 4.427 Executing script cache:clear [KO]
#21 4.477  [KO]
#21 4.477 Script cache:clear returned with error code 255
#21 4.477 !!  PHP Fatal error:  Uncaught Error: Class "Symfony\Bundle\MonologBundle\MonologBundle" not found in /srv/app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php:131
#21 4.477 !!  Stack trace:
#21 4.477 !!  #0 /srv/app/vendor/symfony/http-kernel/Kernel.php(382): App\Kernel->registerBundles()
#21 4.477 !!  #1 /srv/app/vendor/symfony/http-kernel/Kernel.php(768): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#21 4.477 !!  #2 /srv/app/vendor/symfony/http-kernel/Kernel.php(128): Symfony\Component\HttpKernel\Kernel->preBoot()
#21 4.477 !!  #3 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(166): Symfony\Component\HttpKernel\Kernel->boot()
#21 4.477 !!  #4 /srv/app/vendor/symfony/framework-bundle/Console/Application.php(72): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#21 4.477 !!  #5 /srv/app/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
#21 4.477 !!  #6 /srv/app/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php(54): Symfony\Component\Console\Application->run()
#21 4.477 !!  #7 /srv/app/vendor/autoload_runtime.php(29): Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner->run()
#21 4.477 !!  #8 /srv/app/bin/console(11): require_once('...')
#21 4.477 !!  #9 {main}
#21 4.477 !!    thrown in /srv/app/vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php on line 131
#21 4.477 !!
#21 4.478 Script @auto-scripts was called via post-install-cmd
```

Here is my `composer.json`

```JSON
{
    "name": "symfony/skeleton",
    "type": "project",
    "license": "MIT",
    "description": "A minimal Symfony project recommended to create bare bones applications",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^6.2",
        "symfony/console": "6.0.*",
        "symfony/dotenv": "6.0.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.0.*",
        "symfony/runtime": "6.0.*",
        "symfony/twig-bundle": "6.0.*",
        "symfony/yaml": "6.0.*",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "6.0.*",
            "docker": true
        }
    },
    "require-dev": {
        "phpstan/phpstan": "^1.5",
        "phpunit/phpunit": "^9.5",
        "squizlabs/php_codesniffer": "*",
        "symfony/browser-kit": "6.0.*",
        "symfony/css-selector": "6.0.*",
        "symfony/debug-bundle": "6.0.*",
        "symfony/maker-bundle": "^1.38",
        "symfony/monolog-bundle": "^3.0",
        "symfony/phpunit-bridge": "^6.0",
        "symfony/stopwatch": "6.0.*",
        "symfony/web-profiler-bundle": "6.0.*"
    }
}
```

My `docker-compose.yaml` is from this project, I didn't touch it.

Thx for your help. I hope I didn't forget to mention anything.

**Comment by 0-Yorick-0** [comment]
Ok I finally found the solution.

It was the symfony/monolog-bundle which was in dev requirements in my `composer.json`, but in `['all' => true]`in my `config/bundles.php`.

So there was a conflict between the result of `composer symfony:dump-env prod` and `composer run-script --no-dev post-install-cmd`.

So I juste moved the bundle in the `require`section and everything went right.

Hope it will help someone else.
