### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by o7-sol** [dunglas/symfony-docker#239]
When I run `docker-compose up` it fails everytime with this error:

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 70, in project_from_options
  File "compose/cli/command.py", line 146, in get_project
  File "compose/cli/command.py", line 206, in get_project_name
  File "posixpath.py", line 383, in abspath
FileNotFoundError: [Errno 2] No such file or directory
[6398] Failed to execute script docker-compose
```

This happens with the fresh version of this repository

**Comment by o7-sol** [comment]
Restarting WSL Ubuntu helps...
